-- ============================================================================
-- MANILOAN SUPABASE DATABASE PERFORMANCE OPTIMIZATION SCRIPT
-- Run this script in Supabase SQL Editor (https://qqibelflabhmgpkshigb.supabase.co)
-- ============================================================================

-- 1. Create chat_history table if not exists
CREATE TABLE IF NOT EXISTS public.chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    messages JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create unique index on session_id for O(1) lookups and atomic upsert operations
CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_history_session_id 
ON public.chat_history (session_id);

-- 3. Create index on created_at for fast time-series queries & cleanup
CREATE INDEX IF NOT EXISTS idx_chat_history_created_at 
ON public.chat_history (created_at DESC);

-- 4. Create loan_applications table if not exists
CREATE TABLE IF NOT EXISTS public.loan_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    applicant_age INT,
    income NUMERIC(12,2),
    loan_amount_requested NUMERIC(12,2),
    tenure_months INT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create index on user_id for fast user loan history queries
CREATE INDEX IF NOT EXISTS idx_loan_applications_user_id 
ON public.loan_applications (user_id);

CREATE INDEX IF NOT EXISTS idx_loan_applications_created_at 
ON public.loan_applications (created_at DESC);

-- 6. Enable Row Level Security (RLS) policies for user data protection
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loan_applications ENABLE ROW LEVEL SECURITY;

-- Allow public anonymous reads/writes for chat_history by session_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'chat_history' AND policyname = 'Allow public access to chat_history'
    ) THEN
        CREATE POLICY "Allow public access to chat_history" 
        ON public.chat_history FOR ALL 
        USING (true) 
        WITH CHECK (true);
    END IF;
END $$;

-- Allow authenticated users to view/create their own loan applications
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'loan_applications' AND policyname = 'Users access own loan applications'
    ) THEN
        CREATE POLICY "Users access own loan applications" 
        ON public.loan_applications FOR ALL 
        USING (auth.uid() = user_id) 
        WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;
